// Code generated by "sloth -out=Receive,Response,proto -mod=../model -fun=get,set"; DO NOT EDIT.

package proto

type proto struct {
	recv *Tlv
	resp *Tlv
}

type Proto interface {
	GetRecv() *Tlv
	SetRecv(val *Tlv) Proto
	GetResp() *Tlv
	SetResp(val *Tlv) Proto
}

func NewProto() Proto {
	return &proto{}
}

func (p *proto) GetRecv() *Tlv {
	return p.recv
}

func (p *proto) SetRecv(val *Tlv) Proto {
	p.recv = val
	return p
}

func (p *proto) GetResp() *Tlv {
	return p.resp
}

func (p *proto) SetResp(val *Tlv) Proto {
	p.resp = val
	return p
}
